% TLS Dynamics Simulation: Verifying Excitation Mechanism via Soft Clipping + LPF
clear; clc; close all;

%% 1. Parameters
% TLS parameters
T1 = 500;
T2 = 300;
Omega = 0.01;
rho30 = -1;

% Pulse parameters
T_pulse = 100;
t0 = 200;
A_SO = 7;
A_ref1 = 25;

% Frequencies
n = 1:5;
omega = 0.18 * n;
max_omega = max(omega); % Highest original frequency is 0.90

% SO Coefficients from the paper
c_SO = [-0.156 + 0.3311i, ...
    -0.862 - 1.042i, ...
    2.341 - 0.601i, ...
    -0.502 + 2.634i, ...
    -1.820 - 1.322i];

% Flat Spectrum Coefficients
c_rms = sqrt(mean(abs(c_SO).^2));
c_flat = c_rms * ones(1, 5);

%% 2. Define Original Signal Functions
f_SO = @(t) A_SO * sum(real(c_SO .* exp(1i * omega .* t))) * exp(-(t-t0)^2 / T_pulse^2);
f_ref2 = @(t) A_SO * sum(real(c_flat .* exp(1i * omega .* t))) * exp(-(t-t0)^2 / T_pulse^2);

%% 3. Generate Time-Domain Vectors & Apply Clipping
t_vec = linspace(0, 600, 5000);
dt = t_vec(2) - t_vec(1);
Fs = 1 / dt; 
L = length(t_vec);

sig_SO = zeros(size(t_vec));
sig_ref2 = zeros(size(t_vec));

for k = 1:length(t_vec)
    sig_SO(k) = f_SO(t_vec(k));
    sig_ref2(k) = f_ref2(t_vec(k));
end

% P-Norm Soft Clipper
clip_limit = 15; 
clip_sharpness = 10; 
p_clip = @(x, L_val, p) x ./ (1 + abs(x/L_val).^p).^(1/p);

% Apply initial clip (this introduces high frequencies)
sig_SO_clipped_raw = p_clip(sig_SO, clip_limit, clip_sharpness);
sig_ref2_clipped_raw = p_clip(sig_ref2, clip_limit, clip_sharpness);

%% 4. Ideal Low-Pass Filter (Remove Added High Frequencies)
% Create frequency vector for the FFT
df = Fs / L;
f_vec_fft = (0:L-1) * df;
omega_fft = 2 * pi * f_vec_fft;

% Wrap frequencies to handle the two-sided spectrum correctly (Nyquist)
omega_fft(omega_fft > pi*Fs) = omega_fft(omega_fft > pi*Fs) - 2*pi*Fs;

% Create an ideal Low-Pass Filter mask. 
% We set the cutoff slightly above max_omega (0.90) to preserve the original signal,
% but kill all the high-frequency harmonics generated by clipping.
omega_cutoff = 1.0; 
LPF_mask = abs(omega_fft) <= omega_cutoff;

% Filter SO Clipped Signal
Y_SO_clip = fft(sig_SO_clipped_raw);
Y_SO_clip_clean = Y_SO_clip .* LPF_mask;
sig_SO_clip_clean = real(ifft(Y_SO_clip_clean));

% Filter Ref2 Clipped Signal
Y_ref2_clip = fft(sig_ref2_clipped_raw);
Y_ref2_clip_clean = Y_ref2_clip .* LPF_mask;
sig_ref2_clip_clean = real(ifft(Y_ref2_clip_clean));

% Create interpolating functions so ODE45 can evaluate the cleaned signals at any time step
f_SO_clip_clean = @(t) interp1(t_vec, sig_SO_clip_clean, t, 'spline', 0);
f_ref2_clip_clean = @(t) interp1(t_vec, sig_ref2_clip_clean, t, 'spline', 0);

%% 5. Calculate Frequency Response for Plotting (Single-Sided)
f_vec_plot = Fs * (0:(L/2)) / L;       
omega_vec_plot = 2 * pi * f_vec_plot;       

% SO Original
Y_SO = fft(sig_SO);
P1_SO = abs(Y_SO/L); P1_SO = P1_SO(1:L/2+1); P1_SO(2:end-1) = 2*P1_SO(2:end-1);

% SO Clipped AND Cleaned
P1_SO_clip = abs(Y_SO_clip_clean/L); P1_SO_clip = P1_SO_clip(1:L/2+1); P1_SO_clip(2:end-1) = 2*P1_SO_clip(2:end-1);

% Ref2 Original
Y_ref2 = fft(sig_ref2);
P1_ref2 = abs(Y_ref2/L); P1_ref2 = P1_ref2(1:L/2+1); P1_ref2(2:end-1) = 2*P1_ref2(2:end-1);

% Ref2 Clipped AND Cleaned
P1_ref2_clip = abs(Y_ref2_clip_clean/L); P1_ref2_clip = P1_ref2_clip(1:L/2+1); P1_ref2_clip(2:end-1) = 2*P1_ref2_clip(2:end-1);

%% 6. Solve Density Matrix ODEs
rho_init = [0; 0; -1];
tspan = [0 600];

ode_system = @(t, rho, func) [ ...
    rho(2) - rho(1)/T2; ...
    -rho(1) - rho(2)/T2 + 2*Omega*func(t)*rho(3); ...
    -2*Omega*func(t)*rho(2) - (rho(3)-rho30)/T1 ];

% Solve using the cleaned interpolation functions
[t_SO, rho_SO] = ode45(@(t, rho) ode_system(t, rho, f_SO), tspan, rho_init);
[t_ref2, rho_ref2] = ode45(@(t, rho) ode_system(t, rho, f_ref2), tspan, rho_init);
[t_SO_clip, rho_SO_clip] = ode45(@(t, rho) ode_system(t, rho, f_SO_clip_clean), tspan, rho_init);
[t_ref2_clip, rho_ref2_clip] = ode45(@(t, rho) ode_system(t, rho, f_ref2_clip_clean), tspan, rho_init);

%% 7. Plotting
figure('Name', 'Mechanism Verification: LPF Band-Limited Clipped Signals', 'Position', [100, 50, 900, 900]);

% Subplot 1: Time Domain
ax1 = subplot(3, 1, 1);
plot(t_vec, sig_SO, 'Color', [0 0.4470 0.7410 0.3], 'LineWidth', 2); hold on;
plot(t_vec, sig_SO_clip_clean, '-', 'Color', [0 0.4470 0.7410], 'LineWidth', 1.5);
plot(t_vec, sig_ref2, 'Color', [0.4660 0.6740 0.1880 0.3], 'LineWidth', 2);
plot(t_vec, sig_ref2_clip_clean, ':', 'Color', [0.4660 0.6740 0.1880], 'LineWidth', 1.5);
yline(clip_limit, 'k--', 'Initial Clip Target', 'LabelHorizontalAlignment', 'left');
yline(-clip_limit, 'k--');
title('Time Domain: Original vs. Band-Limited Clipped Signals');
xlabel('Time'); ylabel('Amplitude'); xlim([0 600]); grid on;
legend('SO Orig', 'SO Clip+LPF', 'Ref2 Orig', 'Ref2 Clip+LPF', 'Location', 'best');

% Subplot 2: Frequency Response
ax2 = subplot(3, 1, 2);
plot(omega_vec_plot, P1_SO, 'Color', [0 0.4470 0.7410 0.3], 'LineWidth', 2); hold on;
plot(omega_vec_plot, P1_SO_clip, '-', 'Color', [0 0.4470 0.7410], 'LineWidth', 1.5);
plot(omega_vec_plot, P1_ref2, 'Color', [0.4660 0.6740 0.1880 0.3], 'LineWidth', 2);
plot(omega_vec_plot, P1_ref2_clip, ':', 'Color', [0.4660 0.6740 0.1880], 'LineWidth', 1.5);
title('Frequency Response (Strictly Band-Limited to \omega \leq 1.0)');
xlabel('Angular Frequency (\omega)'); ylabel('|P1(\omega)|');
xlim([0 2]); grid on;
legend('SO Orig', 'SO Clip+LPF', 'Ref2 Orig', 'Ref2 Clip+LPF', 'Location', 'best');

% Subplot 3: Population Inversion
ax3 = subplot(3, 1, 3);
plot(t_SO, rho_SO(:,3), 'Color', [0 0.4470 0.7410 0.3], 'LineWidth', 2); hold on;
plot(t_SO_clip, rho_SO_clip(:,3), '-', 'Color', [0 0.4470 0.7410], 'LineWidth', 1.5);
plot(t_ref2, rho_ref2(:,3), 'Color', [0.4660 0.6740 0.1880 0.3], 'LineWidth', 2);
plot(t_ref2_clip, rho_ref2_clip(:,3), ':', 'Color', [0.4660 0.6740 0.1880], 'LineWidth', 1.5);
yline(0, 'k-', 'Zero Inversion', 'LabelHorizontalAlignment', 'left');
title('Excitation Verification (\rho_3 = \rho_{22} - \rho_{11})');
xlabel('Time'); ylabel('Population Inversion (\rho_3)');
ylim([-1 1.1]); xlim([0 600]); grid on;
legend('SO Full', 'SO Clip+LPF', 'Ref2 Full', 'Ref2 Clip+LPF', 'Location', 'best');

linkaxes([ax1, ax3], 'x');