clear; clc
% main_Fabri_Perot.m
% Simulates the field at the input, inside and outside of a Fabry-Perot cavity
% driven by a superoscillating input signal generated by generate_signal_Eli.m.

% 1. Fabry-Perot Cavity Parameters
L = 10; % Cavity length
c = 1;  % Speed of light
R = 0.9; % Intensity reflectivity
r1 = sqrt(R); % Amplitude reflection coefficient for mirror 1
t1 = sqrt(1 - R); % Amplitude transmission coefficient for mirror 1
r2 = sqrt(R); % Amplitude reflection coefficient for mirror 2
t2 = sqrt(1 - R); % Amplitude transmission coefficient for mirror 2

% 2. Initialize SO signal to match the first two cavity notches (m=2 and m=1)
global current_m;
current_m = 2;
A_init = 10;
Omega_init = current_m * pi * c / L;
delta_init = pi * c / L;

% 3. Call the interactive signal plotting script to create the first figure and GUI.
interactive_Eli_signal;

% 4. Plot cavity frequency response on top of the frequency plot (ax2)
H_cavity = (-t1 * t2) ./ (1 - r1 * r2 * exp(-1i * 2 * freq_axis * L / c));
H_cavity_abs = abs(H_cavity) / max(abs(H_cavity));

hold(ax2, 'on');
plot(ax2, freq_axis, H_cavity_abs, '--', 'Color', '#0072BD', 'LineWidth', 1.5, 'DisplayName', 'Cavity Response $|H(\omega)|$');
legend(ax2, 'show', 'Location', 'best', 'Interpreter', 'latex');
hold(ax2, 'off');

% 5. Interactive Simulation of the field in Time and Space
fig2 = figure('Name', 'Fabry-Perot Cavity Time Simulation', 'Position', [150, 150, 1000, 450]);

% Create axes and make room for buttons
ax3 = axes(fig2, 'Position', [0.1 0.25 0.85 0.65]);
hold(ax3, 'on');

% Buttons to move notches up and down the frequency comb
% Placed in the first figure (fig) above the sliders (y=140)
btn_up = uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', 'Notches Up (+)', ...
    'Position', [390, 140, 150, 40], 'FontSize', 12, 'FontWeight', 'bold');
btn_down = uicontrol('Parent', fig, 'Style', 'pushbutton', 'String', 'Notches Down (-)', ...
    'Position', [220, 140, 150, 40], 'FontSize', 12, 'FontWeight', 'bold');

% Button Callbacks
btn_up.Callback = @(src, event) shift_notches(1, c, L, sld_Omega, txt_Omega, sld_delta, txt_delta, fig);
btn_down.Callback = @(src, event) shift_notches(-1, c, L, sld_Omega, txt_Omega, sld_delta, txt_delta, fig);

% Define space axes for the 3 regions
z_in = linspace(-L, 0, 300);
z_cav = linspace(0, L, 300);
z_out = linspace(L, 2*L, 300);

% Initialize plot lines (Left Axis for Amplitude)
yyaxis(ax3, 'left');
p_in = plot(ax3, z_in, zeros(size(z_in)), 'b','LineStyle', '-',  'LineWidth', 1.5, 'DisplayName', 'Input Region (z < 0)');
p_cav = plot(ax3, z_cav, zeros(size(z_cav)), 'r', 'LineStyle', '-', 'LineWidth', 1.5, 'DisplayName', 'Inside Cavity (0 \leq z \leq L)');
p_out = plot(ax3, z_out, zeros(size(z_out)), 'm', 'LineStyle', '-', 'LineWidth', 1.5, 'DisplayName', 'Output Region (z > L)');
ylabel(ax3, '\boldmath$\mathbf{Re\{E(z,t)\}}$', 'Interpreter', 'latex');
ax3.YAxis(1).Color = 'k';

% Initialize Instantaneous Frequency lines (Right Axis)
yyaxis(ax3, 'right');
p_if_in = plot(ax3, z_in, zeros(size(z_in)), '-', 'Color', '#006400', 'LineWidth', 1.2, 'DisplayName', 'Inst. Freq.');
p_if_cav = plot(ax3, z_cav, zeros(size(z_cav)), '-', 'Color', '#006400', 'LineWidth', 1.2, 'HandleVisibility', 'off');
p_if_out = plot(ax3, z_out, zeros(size(z_out)), '-', 'Color', '#006400', 'LineWidth', 1.2, 'HandleVisibility', 'off');
ylabel(ax3, '\boldmath$\mathbf{Inst. \ Freq.}$', 'Interpreter', 'latex');
ax3.YAxis(2).Color = '#006400';

% Dashed line for theoretical max frequency
freq_line2 = yline(ax3, Omega_init, '--', 'Color', '#006400', 'HandleVisibility', 'off', 'LineWidth', 1.5);

% Formatting the axes (back to left for grid/limits)
yyaxis(ax3, 'left');
xline(ax3, 0, 'k--', 'LineWidth', 2, 'HandleVisibility', 'off');
xline(ax3, L, 'k--', 'LineWidth', 2, 'HandleVisibility', 'off');
xlabel(ax3, '\boldmath$z \ \mathbf{axis}$', 'Interpreter', 'latex');
title(ax3, 'Field Propagation in Fabry-Perot Cavity', 'Interpreter', 'latex');
legend(ax3, 'Location', 'best', 'Interpreter', 'latex');
grid(ax3, 'on');

PlotUtils.styleAxes(gca);

% Animation loop setup
t_sim = 0;
dt_sim = 0.1;

% Run simulation as long as both figures are open
while ishandle(fig) && ishandle(fig2)
    % Get current parameters from the sliders of the first figure
    A_cur = sld_A.Value;
    Omega_cur = sld_Omega.Value;
    delta_cur = sld_delta.Value;
    
    a = [A_cur, -(A_cur - 1)];
    omega = [Omega_cur, Omega_cur - delta_cur];
    
    % Initialize total fields
    E_in_n = zeros(2, length(z_in));
    E_cav_n = zeros(2, length(z_cav));
    E_out_n = zeros(2, length(z_out));
    
    for n = 1:2
        % Common denominator term for the cavity
        den = 1 - r1 * r2 * exp(-1i * 2 * omega(n) * L / c);
        
        % 1. Input region (Incident + Reflected waves)
        E_inc = a(n) * exp(1i * omega(n) * (t_sim - z_in/c));
        E_ref = a(n) * (r1 - (t1^2 * r2 * exp(-1i * 2 * omega(n) * L / c)) / den) .* exp(1i * omega(n) * (t_sim + z_in/c));
        E_in_n(n, :) = E_inc + E_ref;
        
        % 2. Cavity region (Forward + Backward waves)
        E_cav_term = (1i * t1 * a(n) / den) * ( exp(1i * omega(n) * (t_sim - z_cav/c)) + r2 * exp(1i * omega(n) * (t_sim + z_cav/c - 2*L/c)) );
        E_cav_n(n, :) = E_cav_term;
        
        % 3. Output region (Transmitted forward wave)
        E_out_term = (-t1 * t2 * a(n) / den) * exp(1i * omega(n) * (t_sim - z_out/c));
        E_out_n(n, :) = E_out_term;
    end
    
    % Sum over modes
    E_in_tot = E_in_n(1,:) + E_in_n(2,:);
    E_cav_tot = E_cav_n(1,:) + E_cav_n(2,:);
    E_out_tot = E_out_n(1,:) + E_out_n(2,:);
    
    % Analytical instantaneous frequency using the complex exact formula
    % By passing the evaluated modes as 'amps' and t=0, the function computes the correct w_inst
    inst_freq_in = compute_instantaneous_frequency_analytical_fourier_series(E_in_n, omega, 0);
    inst_freq_cav = compute_instantaneous_frequency_analytical_fourier_series(E_cav_n, omega, 0);
    inst_freq_out = compute_instantaneous_frequency_analytical_fourier_series(E_out_n, omega, 0);
    
    % Update Amplitude Plot Y-data
    p_in.YData = real(E_in_tot);
    p_cav.YData = real(E_cav_tot);
    p_out.YData = real(E_out_tot);
    
    % Update Instantaneous Frequency Y-data
    p_if_in.YData = inst_freq_in;
    p_if_cav.YData = inst_freq_cav;
    p_if_out.YData = inst_freq_out;
    
    % Update dashed line
    freq_line2.Value = Omega_cur;
    
    % Calculate the theoretical maximum envelope to keep Y-axis constant (Left Axis)
    max_in_env = 0;
    max_cav_env = 0;
    max_out_env = 0;
    
    for n = 1:2
        den = 1 - r1 * r2 * exp(-1i * 2 * omega(n) * L / c);
        r_tot = r1 - (t1^2 * r2 * exp(-1i * 2 * omega(n) * L / c)) / den;
        
        max_in_env = max_in_env + abs(a(n)) * (1 + abs(r_tot));
        max_cav_env = max_cav_env + (t1 * abs(a(n)) / abs(den)) * (1 + r2);
        max_out_env = max_out_env + (t1 * t2 * abs(a(n)) / abs(den));
    end
    
    max_theoretical = max([max_in_env, max_cav_env, max_out_env]);
    if max_theoretical == 0
        max_theoretical = 1; % fallback
    end
    
    target_ylim_amp = max_theoretical * 1.1; % 10% padding
    
    yyaxis(ax3, 'left');
    current_ylim_amp = ylim(ax3);
    if abs(target_ylim_amp - current_ylim_amp(2)) / current_ylim_amp(2) > 0.02
        ylim(ax3, [-target_ylim_amp, target_ylim_amp]);
        ax3.YAxis(1).TickValuesMode = 'auto';
        ax3.YAxis(1).TickLabelsMode = 'auto';
    end
    
    % Adjust Y-limits for Inst Freq (Right Axis)
    % Cap it relative to Omega so singularities don't ruin the plot
    yyaxis(ax3, 'right');
    target_ylim_freq = max(5 * Omega_cur, 2.0);
    current_ylim_freq = ylim(ax3);
    if abs(target_ylim_freq - current_ylim_freq(2)) / current_ylim_freq(2) > 0.05 || current_ylim_freq(1) ~= -target_ylim_freq*0.5
        ylim(ax3, [-target_ylim_freq*0.5, target_ylim_freq*1.5]);
        ax3.YAxis(2).TickValuesMode = 'auto';
        ax3.YAxis(2).TickLabelsMode = 'auto';
    end
    
    drawnow;
    t_sim = t_sim + dt_sim;
end


%% Helper Function for Button Callbacks
function shift_notches(direction, c, L, sld_Omega, txt_Omega, sld_delta, txt_delta, fig1)
    global current_m;
    
    % Recover m if it got lost, assuming it's around Omega / (pi*c/L)
    if isempty(current_m)
        current_m = round(sld_Omega.Value / (pi * c / L));
    end
    
    new_m = current_m + direction;
    if new_m < 2
        new_m = 2; % Prevent going below the first two notches (m=2 and m=1)
    end
    
    new_Omega = new_m * pi * c / L;
    new_delta = pi * c / L;
    
    % Clamp to slider limits
    if new_Omega > sld_Omega.Max
        new_Omega = sld_Omega.Max;
        new_m = floor(new_Omega / (pi * c / L));
        new_Omega = new_m * pi * c / L;
    elseif new_Omega < sld_Omega.Min
        new_Omega = sld_Omega.Min;
        new_m = ceil(new_Omega / (pi * c / L));
        new_Omega = new_m * pi * c / L;
    end
    
    if new_delta > sld_delta.Max
        new_delta = sld_delta.Max;
    elseif new_delta < sld_delta.Min
        new_delta = sld_delta.Min;
    end
    
    current_m = new_m;
    
    % Update UI Sliders and Texts
    sld_Omega.Value = new_Omega;
    txt_Omega.String = num2str(new_Omega, '%.2f');
    
    sld_delta.Value = new_delta;
    txt_delta.String = num2str(new_delta, '%.3f');
    
    % Trigger the interactive_Eli_signal's listener to update its plots
    if isfield(fig1.UserData, 'update_plot_cb')
        cb = fig1.UserData.update_plot_cb;
        cb(sld_Omega, []); % Call the callback with dummy event data
    end
end
